{
  jurisdictions {
    edges {
      node {
        name
        legislature: organizations(classification: "legislature", first: 1) {
          edges {
            node {
              name
              classification
              children(last: 2) {
                edges {
                  node {
                    name
                    classification
                    id
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
