{
  jurisdictions {
    edges {
      node {
        name
        legislativeSessions {
          edges {
            node {
              name
            }
          }
        }
        legislature: organizations(classification: "legislature", first: 1) {
          edges {
            node {
              name
              classification
              children(first: 5) {
                edges {
                  node {
                    name
                    classification
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}